name: Manual Test
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  manual-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: Long-running step (click Cancel Workflow and make sure the job stops immediately)
        shell: signal-fanout {0}
        run: |
          for i in $(seq 1 30); do echo "$(date): $i"; sleep 1; done
